### ISSUE TITLE
I am getting some npm error posting here please check

### ISSUE THREAD

**Issue by varunsureka** [topheman/vanilla-es6-jspm#5]
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "ins
tall"
npm ERR! node v4.3.1
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE
npm ERR! vanilla-es6-jspm@0.10.3 postinstall: `jspm install && npm run webdriver-manager-update`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vanilla-es6-jspm@0.10.3 postinstall script 'jspm install && npm run webdriver-manager-update'.
npm ERR! This is most likely a problem with the vanilla-es6-jspm package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     jspm install && npm run webdriver-manager-update
npm ERR! You can get their info via:
npm ERR!     npm owner ls vanilla-es6-jspm
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\ES6\vanilla-es6-jspm\npm-debug.log

**Comment by topheman** [comment]
Can you try running `./node_modules/.bin/jspm install && npm run webdriver-manager-update` at the root of the project ?

I spotted a little problem on install on node v4 with phantomjs that I fixed on https://github.com/topheman/vanilla-es6-jspm/commit/880f97adadfad4e38f4f0702cd38b26f446aad76 - please git pull the latest version of the master branch and make a fresh install.

If the bug stays, please provide the whole log. I tried a fresh install with node v4 on my laptop that works and the [tests are green](https://travis-ci.org/topheman/vanilla-es6-jspm).
